/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Game;

import java.util.Random;

/**
 *
 * @author Lloyd
 */
public class Africa extends javax.swing.JFrame {

    /**
     * Creates new form Africa
     */
    AfricaQuestion africa= new AfricaQuestion();
    
    int points=0;
    
    
    
    public Africa() {
        initComponents();
        AfricaQuestionWindow.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialogNewContinent = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        buttonSouthAmerica = new javax.swing.JButton();
        buttonAustralia = new javax.swing.JButton();
        buttonEurope = new javax.swing.JButton();
        buttonAsia = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        buttonNorthAmerica = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        backButtonAfrica = new javax.swing.JButton();
        AfricaQuestionWindow = new javax.swing.JPanel();
        jLabelDiceResult = new javax.swing.JLabel();
        questiontext = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        DiceAfrica = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pointsLabel = new javax.swing.JLabel();
        pointsDisplay = new javax.swing.JLabel();
        CheckAnswerResult = new javax.swing.JLabel();
        LabelPointsNeeded = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jDialogNewContinent.setMinimumSize(new java.awt.Dimension(550, 550));
        jDialogNewContinent.setPreferredSize(new java.awt.Dimension(550, 550));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("You are an expert on African history! Choose your next destination:");

        buttonSouthAmerica.setText("South America");
        buttonSouthAmerica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSouthAmericaMouseClicked(evt);
            }
        });
        buttonSouthAmerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSouthAmericaActionPerformed(evt);
            }
        });

        buttonAustralia.setText("Australia");
        buttonAustralia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAustraliaMouseClicked(evt);
            }
        });
        buttonAustralia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAustraliaActionPerformed(evt);
            }
        });

        buttonEurope.setText("Europe");
        buttonEurope.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEuropeMouseClicked(evt);
            }
        });

        buttonAsia.setText("Asia");
        buttonAsia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAsiaMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Congratulations!!");

        buttonNorthAmerica.setText("North America");
        buttonNorthAmerica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNorthAmericaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialogNewContinentLayout = new javax.swing.GroupLayout(jDialogNewContinent.getContentPane());
        jDialogNewContinent.getContentPane().setLayout(jDialogNewContinentLayout);
        jDialogNewContinentLayout.setHorizontalGroup(
            jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                    .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                        .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel4))
                            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonSouthAmerica)
                                    .addComponent(buttonAustralia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonEurope, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAsia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonNorthAmerica, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogNewContinentLayout.setVerticalGroup(
            jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonNorthAmerica)
                .addGap(18, 18, 18)
                .addComponent(buttonSouthAmerica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAustralia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonEurope, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAsia)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        backButtonAfrica.setBackground(new java.awt.Color(0, 153, 204));
        backButtonAfrica.setForeground(new java.awt.Color(240, 240, 240));
        backButtonAfrica.setText("Back");
        backButtonAfrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonAfricaActionPerformed(evt);
            }
        });

        submit.setText("submit");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);

        buttonGroup1.add(jRadioButton3);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AfricaQuestionWindowLayout = new javax.swing.GroupLayout(AfricaQuestionWindow);
        AfricaQuestionWindow.setLayout(AfricaQuestionWindowLayout);
        AfricaQuestionWindowLayout.setHorizontalGroup(
            AfricaQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AfricaQuestionWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AfricaQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questiontext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AfricaQuestionWindowLayout.createSequentialGroup()
                        .addGap(0, 147, Short.MAX_VALUE)
                        .addComponent(submit))
                    .addComponent(jLabelDiceResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(AfricaQuestionWindowLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(AfricaQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AfricaQuestionWindowLayout.setVerticalGroup(
            AfricaQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AfricaQuestionWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDiceResult, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(questiontext, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(submit)
                .addContainerGap())
        );

        DiceAfrica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/southamericabackground/dice-md.png"))); // NOI18N
        DiceAfrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiceAfricaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DiceAfricaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DiceAfricaMouseEntered(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome to Africa!");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("Click on the dice to roll it");

        pointsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        pointsLabel.setForeground(new java.awt.Color(255, 255, 255));
        pointsLabel.setText("Points:");

        pointsDisplay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pointsDisplay.setForeground(new java.awt.Color(255, 255, 255));

        CheckAnswerResult.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        CheckAnswerResult.setForeground(new java.awt.Color(0, 255, 0));
        CheckAnswerResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckAnswerResultMouseEntered(evt);
            }
        });

        LabelPointsNeeded.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelPointsNeeded.setForeground(new java.awt.Color(255, 255, 255));
        LabelPointsNeeded.setText("Beat this level by earning 40,000 points!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(DiceAfrica))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButtonAfrica))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(AfricaQuestionWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(CheckAnswerResult, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pointsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pointsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelPointsNeeded)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pointsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(pointsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelPointsNeeded)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiceAfrica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                                .addComponent(backButtonAfrica))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 42, Short.MAX_VALUE)
                                .addComponent(CheckAnswerResult, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(AfricaQuestionWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(62, 62, 62))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/AfricaBackground/newafrica.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DiceAfricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceAfricaMouseClicked
        // TODO add your handling code here:
        Random roll= new Random();
        int result= 1+ roll.nextInt(6);//int between 1-6 inclusive
        AfricaQuestionWindow.setVisible(true);
        questiontext.setText(africa.showQuestion());//sets returned string as question

        if(questiontext.getText().contains("When did the African island"))
        {
            jRadioButton1.setText("1975");
            jRadioButton2.setText("1976");
            jRadioButton3.setText("1977");
            jRadioButton4.setText("1978");
            

        }
        else if(questiontext.getText().contains("Who founded Timbuctu?"))
        {

            jRadioButton1.setText("Hatsheput");
            jRadioButton2.setText("Harry Potter");
            jRadioButton3.setText("Touareg");
            jRadioButton4.setText("Cheick Kongo");

        }
        else if(questiontext.getText().contains("Which of these Egyptian"))
        {

            jRadioButton1.setText("Akhenaten");
            jRadioButton2.setText("Pharoah");
            jRadioButton3.setText("Ramses");
            jRadioButton4.setText("Hatsheput");

        }       
        else if(questiontext.getText().contains("The Berber are the indigenous"))
        {

            jRadioButton1.setText("East");
            jRadioButton2.setText("West");
            jRadioButton3.setText("North");
            jRadioButton4.setText("South ");

        }       
        else if(questiontext.getText().contains("When was Kong obliterated?"))
        {

           jRadioButton1.setText("1895");
            jRadioButton2.setText("1896");
            jRadioButton3.setText("1899");
            jRadioButton4.setText("1898");

        }       
        //Which South African party
        else if(questiontext.getText().contains("Which South African party"))
        {

           jRadioButton1.setText("Republican");
            jRadioButton2.setText("Nationalist");
            jRadioButton3.setText("Democratic");
            jRadioButton4.setText("Dutch");

        }    
        else if(questiontext.getText().contains("Which country was once known as British Basutoland?"))
        {

           jRadioButton1.setText("Cameroon");
            jRadioButton2.setText("Morocco");
            jRadioButton3.setText("Lesotho");
            jRadioButton4.setText("Kenya");

        }    
        //Which African National Congress
        else if(questiontext.getText().contains("Which African National Congress"))
        {

           jRadioButton1.setText("Albert Lutuli");
            jRadioButton2.setText("Idi Amin");
            jRadioButton3.setText("Lesotho");
            jRadioButton4.setText("Kenya");

        }    
        
        //Questions paired with answers
        
        
        
        if(result==1)
        {
            jLabelDiceResult.setText("You rolled a 1!");
            //a
        }
        if(result==2)
        {
            jLabelDiceResult.setText("You rolled a 2!");
            
        }
        if(result==3)
        {
            jLabelDiceResult.setText("You rolled a 3!");
            
        }
        if(result==4)
        {
            jLabelDiceResult.setText("You rolled a 4!");
            
        }
        if(result==5)
        {
            jLabelDiceResult.setText("You rolled a 5!");
            
        }
        if(result==6)
        {
            jLabelDiceResult.setText("You rolled a 6!");
        }
        //invoke a JDialog with the question.
        //have jdialog close on submit
        //rinse and repeat for other continents
        //find a way to move a panel by (int)result
        
    }//GEN-LAST:event_DiceAfricaMouseClicked

    private void backButtonAfricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonAfricaActionPerformed
        // TODO add your handling code here:
        ContinentSelection cs = new ContinentSelection();
        cs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonAfricaActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
       if(buttonGroup1.getSelection()==null)
        {    
            CheckAnswerResult.setVisible(false);
            jLabelDiceResult.setText("Please make a selection");
        }
        else
        {
            AfricaQuestionWindow.setVisible(false);
            
        
            if(questiontext.getText().contains("When did the African island"))
                {

            //jradiobutton2
               if(!(jRadioButton1.isSelected()))
                  {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
                {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                   
                    pointsDisplay.setText(" "+points);

                    }
            
             }
             else if(questiontext.getText().contains("Who founded Timbuctu?"))
             {

            //jradiobutton2
                if(!(jRadioButton3.isSelected()))
                {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
                }
                else
                {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                   
                    pointsDisplay.setText(" "+points);

            }
        }
         else if(questiontext.getText().contains("Which of these Egyptian"))
        {

            //jradiobutton2
            if(!(jRadioButton4.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                   
                    pointsDisplay.setText(" "+points);

            }
        }
         else if(questiontext.getText().contains("The Berber are the indigenous"))
        {

            //jradiobutton2
            if(!(jRadioButton3.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                   
                    pointsDisplay.setText(" "+points);

            }
        }
        else if(questiontext.getText().contains("When was Kong obliterated?"))
        {

            //jradiobutton2
            if(!(jRadioButton1.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                   
                    pointsDisplay.setText(" "+points);

            }
        }
        else if(questiontext.getText().contains("Which South African party"))
        {

            //jradiobutton2
            if(!(jRadioButton2.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                   
                    pointsDisplay.setText(" "+points);

            }
        }
         buttonGroup1.clearSelection();
        
        
        }
        
        
        
    }//GEN-LAST:event_submitMouseClicked

    private void DiceAfricaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceAfricaMouseEntered
        // TODO add your handling code here:
        DiceAfrica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
         if(points>=40000)
        {
        //dialog box for moving to another continent
            jDialogNewContinent.setVisible(true);
            
        }
    }//GEN-LAST:event_DiceAfricaMouseEntered

    private void DiceAfricaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceAfricaMouseExited
        // TODO add your handling code here:
        DiceAfrica.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_DiceAfricaMouseExited

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void CheckAnswerResultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckAnswerResultMouseEntered
        // TODO add your handling code here:
        CheckAnswerResult.setText(null);
    }//GEN-LAST:event_CheckAnswerResultMouseEntered

    private void buttonSouthAmericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSouthAmericaMouseClicked
        // TODO add your handling code here:
        SouthAmerica sa = new SouthAmerica();
        sa.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonSouthAmericaMouseClicked

    private void buttonSouthAmericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSouthAmericaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSouthAmericaActionPerformed

    private void buttonAustraliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAustraliaMouseClicked
        // TODO add your handling code here:
        Australia au = new Australia();
        au.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonAustraliaMouseClicked

    private void buttonAustraliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAustraliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAustraliaActionPerformed

    private void buttonEuropeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEuropeMouseClicked
        // TODO add your handling code here:
        Europe e = new Europe();
        e.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonEuropeMouseClicked

    private void buttonAsiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAsiaMouseClicked
        // TODO add your handling code here:
        Asia a = new Asia();
        a.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonAsiaMouseClicked

    private void buttonNorthAmericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNorthAmericaMouseClicked
        // TODO add your handling code here:
        NorthAmerica n= new NorthAmerica();
        n.setVisible(true);
        this.setVisible(true);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonNorthAmericaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Africa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Africa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Africa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Africa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Africa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AfricaQuestionWindow;
    private javax.swing.JLabel CheckAnswerResult;
    private javax.swing.JLabel DiceAfrica;
    private javax.swing.JLabel LabelPointsNeeded;
    private javax.swing.JButton backButtonAfrica;
    private javax.swing.JButton buttonAsia;
    private javax.swing.JButton buttonAustralia;
    private javax.swing.JButton buttonEurope;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonNorthAmerica;
    private javax.swing.JButton buttonSouthAmerica;
    private javax.swing.JDialog jDialogNewContinent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDiceResult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel pointsDisplay;
    private javax.swing.JLabel pointsLabel;
    private javax.swing.JLabel questiontext;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
