/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Game;

import java.util.Random;
/**
 *
 * @author Lloyd
 */
public class Asia extends javax.swing.JFrame {

    /**
     * Creates new form Asia
     */
    AsiaQuestion a= new AsiaQuestion();
    int points= 0;
    public Asia() {
        initComponents();
        AsiaQuestionWindow.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDialogNewContinent = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonNorthAmerica = new javax.swing.JButton();
        buttonSouthAmerica = new javax.swing.JButton();
        buttonAustralia = new javax.swing.JButton();
        buttonEurope = new javax.swing.JButton();
        buttonAfrica = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        DiceAsia = new javax.swing.JLabel();
        backButtonAsia = new javax.swing.JButton();
        AsiaQuestionWindow = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        AsiaQuestionText = new javax.swing.JLabel();
        jLabelDiceResult = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        CheckAnswerResult = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pointsLabel = new javax.swing.JLabel();
        pointsDisplay = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelPointsNeeded = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jDialogNewContinent.setMinimumSize(new java.awt.Dimension(550, 550));
        jDialogNewContinent.setPreferredSize(new java.awt.Dimension(550, 550));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Congratulations!!");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("You are an expert on Asian history! Choose your next destination:");

        buttonNorthAmerica.setText("North America");
        buttonNorthAmerica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNorthAmericaMouseClicked(evt);
            }
        });

        buttonSouthAmerica.setText("South America");
        buttonSouthAmerica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSouthAmericaMouseClicked(evt);
            }
        });
        buttonSouthAmerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSouthAmericaActionPerformed(evt);
            }
        });

        buttonAustralia.setText("Australia");
        buttonAustralia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAustraliaMouseClicked(evt);
            }
        });
        buttonAustralia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAustraliaActionPerformed(evt);
            }
        });

        buttonEurope.setText("Europe");
        buttonEurope.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEuropeMouseClicked(evt);
            }
        });

        buttonAfrica.setText("Africa");
        buttonAfrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAfricaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialogNewContinentLayout = new javax.swing.GroupLayout(jDialogNewContinent.getContentPane());
        jDialogNewContinent.getContentPane().setLayout(jDialogNewContinentLayout);
        jDialogNewContinentLayout.setHorizontalGroup(
            jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
                    .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                        .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel4))
                            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonSouthAmerica)
                                    .addComponent(buttonAustralia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonEurope, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonNorthAmerica, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAfrica, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogNewContinentLayout.setVerticalGroup(
            jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonNorthAmerica)
                .addGap(18, 18, 18)
                .addComponent(buttonSouthAmerica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAustralia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonEurope, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAfrica, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        DiceAsia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/southamericabackground/dice-md.png"))); // NOI18N
        DiceAsia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiceAsiaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DiceAsiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DiceAsiaMouseExited(evt);
            }
        });

        backButtonAsia.setBackground(new java.awt.Color(0, 153, 255));
        backButtonAsia.setForeground(new java.awt.Color(240, 240, 240));
        backButtonAsia.setText("Back");
        backButtonAsia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonAsiaActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });

        jLabelDiceResult.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AsiaQuestionWindowLayout = new javax.swing.GroupLayout(AsiaQuestionWindow);
        AsiaQuestionWindow.setLayout(AsiaQuestionWindowLayout);
        AsiaQuestionWindowLayout.setHorizontalGroup(
            AsiaQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AsiaQuestionWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AsiaQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AsiaQuestionText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AsiaQuestionWindowLayout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(AsiaQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDiceResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(AsiaQuestionWindowLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AsiaQuestionWindowLayout.setVerticalGroup(
            AsiaQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AsiaQuestionWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDiceResult, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AsiaQuestionText, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(35, 35, 35))
        );

        CheckAnswerResult.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        CheckAnswerResult.setForeground(new java.awt.Color(0, 153, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Click on the dice to roll it");

        pointsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pointsLabel.setForeground(new java.awt.Color(255, 255, 255));
        pointsLabel.setText("Points:");

        pointsDisplay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pointsDisplay.setForeground(new java.awt.Color(255, 255, 255));
        pointsDisplay.setText("0");

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome to Asia!");

        LabelPointsNeeded.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelPointsNeeded.setForeground(new java.awt.Color(255, 255, 255));
        LabelPointsNeeded.setText("Beat this level by earning 40,000 points!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DiceAsia)
                                .addComponent(backButtonAsia))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LabelPointsNeeded)
                        .addGap(88, 88, 88)
                        .addComponent(pointsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pointsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(AsiaQuestionWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CheckAnswerResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(272, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pointsLabel)
                                    .addComponent(pointsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LabelPointsNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(CheckAnswerResult, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AsiaQuestionWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DiceAsia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButtonAsia)
                        .addGap(55, 55, 55))))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/AsiaBackground/newasia.jpg"))); // NOI18N
        jLabel1.setAutoscrolls(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DiceAsiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceAsiaMouseClicked
        // TODO add your handling code here:
        
        Random roll= new Random();
        int result= 1+ roll.nextInt(6);//int between 1-6 inclusive
        int points=0;
        AsiaQuestionWindow.setVisible(true);
        
        jComboBox1.removeAllItems();
        
        AsiaQuestionText.setText(a.showQuestion());
        
        if(result==1)
        {
            jLabelDiceResult.setText("You rolled a 1!");
            //a
        }
        if(result==2)
        {
            jLabelDiceResult.setText("You rolled a 2!");
            
        }
        if(result==3)
        {
            jLabelDiceResult.setText("You rolled a 3!");
            
        }
        if(result==4)
        {
            jLabelDiceResult.setText("You rolled a 4!");
            
        }
        if(result==5)
        {
            jLabelDiceResult.setText("You rolled a 5!");
            
        }
        if(result==6)
        {
            jLabelDiceResult.setText("You rolled a 6!");
        }
         //add contents according to question
         
         if(AsiaQuestionText.getText().contains("The highland border"))
           {
                     jComboBox1.addItem("Select...");
                     jComboBox1.addItem("The Golden Triangle");
                     jComboBox1.addItem("Disneyland");
                     jComboBox1.addItem("The north pole");
                     jComboBox1.addItem("Kentucky");
           }
         else if(AsiaQuestionText.getText().contains("Where did Bhuddism originate?"))
         {
                     jComboBox1.addItem("Select...");
                     jComboBox1.addItem("Texas");
                     jComboBox1.addItem("India");
                     jComboBox1.addItem("China");
                     jComboBox1.addItem("Mongolia");
         
         
         
         }
       else if(AsiaQuestionText.getText().contains("In which Asian country"))
         {
                     jComboBox1.addItem("Select...");
                     jComboBox1.addItem("Burma");
                     jComboBox1.addItem("Thailand");
                     jComboBox1.addItem("China");
                     jComboBox1.addItem("Mongolia");
         
         
         
         }
         else if(AsiaQuestionText.getText().contains("In which present day country did the kingdom of Assyria exist?"))
         {
                     jComboBox1.addItem("Select...");
                     jComboBox1.addItem("Egypt");
                     jComboBox1.addItem("Iran");
                     jComboBox1.addItem("Iraq");
                     jComboBox1.addItem("Morocco");
         
         //for some odd reason this one won't work. no idea why.
         
         }
         else if(AsiaQuestionText.getText().contains("Name the famous"))
         {
                     jComboBox1.addItem("Select...");
                     jComboBox1.addItem("Cyrus The Great");
                     jComboBox1.addItem("Muhammad Ali");
                     jComboBox1.addItem("Mohamed Lawal");
                     jComboBox1.addItem("Badr Hari");
         }
         //
         else if(AsiaQuestionText.getText().contains("Who founded the Mongol"))
         {
                     jComboBox1.addItem("Select...");
                     jComboBox1.addItem("Genghis Khan");
                     jComboBox1.addItem("Shang Tsung");
                     jComboBox1.addItem("Barack Obama");
                     
         }
         else if(AsiaQuestionText.getText().contains("In which Arabian city was Prophet Mohammad born?"))
         {
                     jComboBox1.addItem("Select...");
                     jComboBox1.addItem("Riyadh");
                     jComboBox1.addItem("Mecca");
                     jComboBox1.addItem("Khobar");
                     jComboBox1.addItem("Qatif");
                     
         }
          else if(AsiaQuestionText.getText().contains("Which of the earth's"))
         {
                     jComboBox1.addItem("Select...");
                     jComboBox1.addItem("Largest Continent");
                     jComboBox1.addItem("Highest Elevation");
                     jComboBox1.addItem("Lowest Elevation");
                     jComboBox1.addItem("Deepest lake");
                     jComboBox1.addItem("All of the above");
                     
         }
         //
        //invoke a JDialog with the question.
        //have jdialog close on submit
        //rinse and repeat for other continents
        //find a way to move a panel by (int)result
                                               
    }//GEN-LAST:event_DiceAsiaMouseClicked

    private void DiceAsiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceAsiaMouseEntered
            DiceAsia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));   
            CheckAnswerResult.setVisible(false);
    }//GEN-LAST:event_DiceAsiaMouseEntered

    private void DiceAsiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceAsiaMouseExited
DiceAsia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));        
    }//GEN-LAST:event_DiceAsiaMouseExited

    private void backButtonAsiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonAsiaActionPerformed
        // TODO add your handling code here:
        ContinentSelection cs = new ContinentSelection();
        cs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonAsiaActionPerformed

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
        // TODO add your handling code here:
        //AsiaQuestionWindow.setVisible(false);
        //CheckAnswerResult.setVisible(false);
        if(jComboBox1.getSelectedItem().equals("Select..."))
        {    
            CheckAnswerResult.setVisible(false);
            jLabelDiceResult.setText("Please make a selection");
        }
        else
        {
            AsiaQuestionWindow.setVisible(false);
            
         if(AsiaQuestionText.getText().contains("The highland border"))
         {
           if(jComboBox1.getSelectedItem().equals("The Golden Triangle"))
           {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*10;
                pointsDisplay.setText(" "+points);
           
           }
           else
           {
               CheckAnswerResult.setVisible(true);
               CheckAnswerResult.setText("Wrong!");
           }
             
         }
         else if(AsiaQuestionText.getText().contains("Where did Bhuddism originate?"))
         {
           if(jComboBox1.getSelectedItem().equals("India"))
           {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*10;
                pointsDisplay.setText(" "+points);
           
           }
           else
           {
               CheckAnswerResult.setVisible(true);
               CheckAnswerResult.setText("Wrong!");
               
           }
             
         
         
         }
        
         else if(AsiaQuestionText.getText().contains("In which Asian country"))
         {
           if(jComboBox1.getSelectedItem().equals("China"))
           {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*10;
                pointsDisplay.setText(" "+points);
           
           }
           else
           {
               CheckAnswerResult.setVisible(true);
               CheckAnswerResult.setText("Wrong!");
           
           
           }
         
         
         
         }
         else if(AsiaQuestionText.getText().contains("Assyria"))
         {
           if(jComboBox1.getSelectedItem().equals("Iraq"))
           {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*10;
                 pointsDisplay.setText(" "+points);
                
           }
            else
           {
               CheckAnswerResult.setVisible(true);
               CheckAnswerResult.setText("Wrong!");
           
           }
         
         
         }
         else if(AsiaQuestionText.getText().contains("Name the famous"))
         {
           if(jComboBox1.getSelectedItem().equals("Cyrus The Great"))
           {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*10;
                 pointsDisplay.setText(" "+points);
           
           }
           else
           {
               CheckAnswerResult.setVisible(true);
               CheckAnswerResult.setText("Wrong!");
           
           }
          
         }
         //
         else if(AsiaQuestionText.getText().contains("Who founded the Mongol"))
         {
             if(jComboBox1.getSelectedItem().equals("Genghis Khan"))
           {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*10;
                 pointsDisplay.setText(" "+points);
           }
           else
           {
               CheckAnswerResult.setVisible(true);
               CheckAnswerResult.setText("Wrong!");
           
           }
                   
         }
         else if(AsiaQuestionText.getText().contains("In which Arabian"))
         {
           if(jComboBox1.getSelectedItem().equals("Mecca"))
           {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*10;
                 pointsDisplay.setText(" "+points);
           }
           else
           {
               CheckAnswerResult.setVisible(true);
               CheckAnswerResult.setText("Wrong!");
           
           }
                     
         }
          else if(AsiaQuestionText.getText().contains("Which of the earth's"))
         {
                    
             if(jComboBox1.getSelectedItem().equals("All of the above"))
           {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*10;
                 pointsDisplay.setText(" "+points);
           }
           else
           {
               CheckAnswerResult.setVisible(true);
               CheckAnswerResult.setText("Wrong!");
           
           }
                     
         }
        }
        
    }//GEN-LAST:event_submitButtonMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void buttonNorthAmericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNorthAmericaMouseClicked
        // TODO add your handling code here:
        NorthAmerica n= new NorthAmerica();
        n.setVisible(true);
        this.setVisible(true);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonNorthAmericaMouseClicked

    private void buttonSouthAmericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSouthAmericaMouseClicked
        // TODO add your handling code here:
        SouthAmerica sa = new SouthAmerica();
        sa.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonSouthAmericaMouseClicked

    private void buttonSouthAmericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSouthAmericaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSouthAmericaActionPerformed

    private void buttonAustraliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAustraliaMouseClicked
        // TODO add your handling code here:
        Australia au = new Australia();
        au.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonAustraliaMouseClicked

    private void buttonAustraliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAustraliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAustraliaActionPerformed

    private void buttonEuropeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEuropeMouseClicked
        // TODO add your handling code here:
        Europe e = new Europe();
        e.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonEuropeMouseClicked

    private void buttonAfricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAfricaMouseClicked
        // TODO add your handling code here:
        Africa a = new Africa();
        a.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonAfricaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AsiaQuestionText;
    private javax.swing.JPanel AsiaQuestionWindow;
    private javax.swing.JLabel CheckAnswerResult;
    private javax.swing.JLabel DiceAsia;
    private javax.swing.JLabel LabelPointsNeeded;
    private javax.swing.JButton backButtonAsia;
    private javax.swing.JButton buttonAfrica;
    private javax.swing.JButton buttonAustralia;
    private javax.swing.JButton buttonEurope;
    private javax.swing.JButton buttonNorthAmerica;
    private javax.swing.JButton buttonSouthAmerica;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDialog jDialogNewContinent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDiceResult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pointsDisplay;
    private javax.swing.JLabel pointsLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
