package Game;

import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lloyd
 */
public class Australia extends javax.swing.JFrame{

    /**
     * Creates new form Australia
     */
    
    AustraliaQuestion aussie= new AustraliaQuestion();
    
    int points= 0;
   
    public Australia() {
        initComponents();
        AustraliaQuestionWindow.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialogNewContinent = new javax.swing.JDialog();
        buttonAfrica = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonNorthAmerica = new javax.swing.JButton();
        buttonSouthAmerica = new javax.swing.JButton();
        buttonEurope = new javax.swing.JButton();
        buttonAsia = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        DiceAustralia = new javax.swing.JLabel();
        AustraliaQuestionWindow = new javax.swing.JPanel();
        QuestionText = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jLabelDiceResult = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        CheckAnswerResult = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pointsLabel = new javax.swing.JLabel();
        pointsDisplay = new javax.swing.JLabel();
        LabelPointsNeeded = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jDialogNewContinent.setMinimumSize(new java.awt.Dimension(550, 550));
        jDialogNewContinent.setPreferredSize(new java.awt.Dimension(550, 550));

        buttonAfrica.setText("Africa");
        buttonAfrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAfricaMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Congratulations!!");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("You are an expert on Australian history! Choose your next destination:");

        buttonNorthAmerica.setText("North America");
        buttonNorthAmerica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNorthAmericaMouseClicked(evt);
            }
        });

        buttonSouthAmerica.setText("South America");
        buttonSouthAmerica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSouthAmericaMouseClicked(evt);
            }
        });
        buttonSouthAmerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSouthAmericaActionPerformed(evt);
            }
        });

        buttonEurope.setText("Europe");
        buttonEurope.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEuropeMouseClicked(evt);
            }
        });

        buttonAsia.setText("Asia");
        buttonAsia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAsiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialogNewContinentLayout = new javax.swing.GroupLayout(jDialogNewContinent.getContentPane());
        jDialogNewContinent.getContentPane().setLayout(jDialogNewContinentLayout);
        jDialogNewContinentLayout.setHorizontalGroup(
            jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
                    .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                        .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel6))
                            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonSouthAmerica)
                                    .addComponent(buttonEurope, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonNorthAmerica, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAfrica, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAsia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogNewContinentLayout.setVerticalGroup(
            jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonNorthAmerica)
                .addGap(18, 18, 18)
                .addComponent(buttonSouthAmerica)
                .addGap(11, 11, 11)
                .addComponent(buttonAsia)
                .addGap(18, 18, 18)
                .addComponent(buttonEurope, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAfrica, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        DiceAustralia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/southamericabackground/dice-md.png"))); // NOI18N
        DiceAustralia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiceAustraliaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DiceAustraliaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DiceAustraliaMouseEntered(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });

        jLabelDiceResult.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buttonGroup1.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);

        buttonGroup1.add(jRadioButton3);

        buttonGroup1.add(jRadioButton4);

        javax.swing.GroupLayout AustraliaQuestionWindowLayout = new javax.swing.GroupLayout(AustraliaQuestionWindow);
        AustraliaQuestionWindow.setLayout(AustraliaQuestionWindowLayout);
        AustraliaQuestionWindowLayout.setHorizontalGroup(
            AustraliaQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AustraliaQuestionWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AustraliaQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AustraliaQuestionWindowLayout.createSequentialGroup()
                        .addGap(0, 161, Short.MAX_VALUE)
                        .addComponent(submitButton))
                    .addComponent(jLabelDiceResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AustraliaQuestionWindowLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(QuestionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(AustraliaQuestionWindowLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(AustraliaQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AustraliaQuestionWindowLayout.setVerticalGroup(
            AustraliaQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AustraliaQuestionWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDiceResult, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuestionText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(35, 35, 35))
        );

        CheckAnswerResult.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        CheckAnswerResult.setForeground(new java.awt.Color(0, 153, 0));
        CheckAnswerResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckAnswerResultMouseEntered(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome to Australia!");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Click on the dice to roll it");

        pointsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        pointsLabel.setForeground(new java.awt.Color(255, 255, 255));
        pointsLabel.setText("Points:");

        pointsDisplay.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        pointsDisplay.setForeground(new java.awt.Color(255, 255, 255));
        pointsDisplay.setText("0");

        LabelPointsNeeded.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelPointsNeeded.setForeground(new java.awt.Color(255, 255, 255));
        LabelPointsNeeded.setText("Beat this level by earning 40,000 points!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(DiceAustralia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AustraliaQuestionWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckAnswerResult, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(LabelPointsNeeded)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(pointsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pointsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pointsLabel)
                            .addComponent(pointsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelPointsNeeded)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(DiceAustralia)
                        .addGap(152, 152, 152))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CheckAnswerResult, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AustraliaQuestionWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addComponent(jButton1)
                .addGap(74, 74, 74))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/AustraliaBackground/newaustralia.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ContinentSelection cs = new ContinentSelection();
        cs.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DiceAustraliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceAustraliaMouseClicked
        // TODO add your handling code here:
        Random roll= new Random();
        int result= 1+ roll.nextInt(6);//int between 1-6 inclusive
        AustraliaQuestionWindow.setVisible(true);
        QuestionText.setText(aussie.showQuestion());
        
        if(QuestionText.getText().contains("Who was the first Australian Prime Minister?"))
        {
            jRadioButton1.setText("Steve Irwin");
            jRadioButton2.setText("Edmund Barton");
            jRadioButton3.setText("Hector Lombard");
            jRadioButton4.setText("Jesus");
            

        }
        else if(QuestionText.getText().contains("Near which Victorian beach"))
        {
            jRadioButton1.setText("Myrtle Beach");
            jRadioButton2.setText("Virginia Beach");
            jRadioButton3.setText("Cheviot Beach");
            jRadioButton4.setText("Daytona Beach");
            

        }
         else if(QuestionText.getText().contains("Which Australian Prime Minister"))
        {
            jRadioButton1.setText("George Sotiropolous");
            jRadioButton2.setText("Michael Schiavello");
            jRadioButton3.setText("Mark Hunt");
            jRadioButton4.setText("Paul Keating");
            

        }
         else if(QuestionText.getText().contains("Which was the last colony"))
        {
            jRadioButton1.setText("Sydney");
            jRadioButton2.setText("Brisbane");
            jRadioButton3.setText("Western Australia");
            jRadioButton4.setText("Christchurch");
            

        }
         else if(QuestionText.getText().contains("Where did the Commonwealth"))
        {
            jRadioButton1.setText("Sydney");
            jRadioButton2.setText("Brisbane");
            jRadioButton3.setText("Melbourne");
            jRadioButton4.setText("Christchurch");
            

        }
        //
        else if(QuestionText.getText().contains("In which year was the Blue Ensign"))
        {
            jRadioButton1.setText("1999");
            jRadioButton2.setText("1953");
            jRadioButton3.setText("1944");
            jRadioButton4.setText("1945");
            

        }
        
        if(result==1)
        {
            jLabelDiceResult.setText("You rolled a 1!");
            //a
        }
        if(result==2)
        {
            jLabelDiceResult.setText("You rolled a 2!");
            
        }
        if(result==3)
        {
            jLabelDiceResult.setText("You rolled a 3!");
            
        }
        if(result==4)
        {
            jLabelDiceResult.setText("You rolled a 4!");
            
        }
        if(result==5)
        {
            jLabelDiceResult.setText("You rolled a 5!");
            
        }
        if(result==6)
        {
            jLabelDiceResult.setText("You rolled a 6!");
        }
        
        //australiaQuestion.showQuestion();
    }//GEN-LAST:event_DiceAustraliaMouseClicked

    private void DiceAustraliaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceAustraliaMouseEntered
        // TODO add your handling code here:
        DiceAustralia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckAnswerResult.setVisible(false);
         if(points>=40000)
        {
        //dialog box for moving to another continent
            jDialogNewContinent.setVisible(true);
            
        }
    }//GEN-LAST:event_DiceAustraliaMouseEntered

    private void DiceAustraliaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceAustraliaMouseExited
        // TODO add your handling code here:
        DiceAustralia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_DiceAustraliaMouseExited

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
                // TODO add your handling code here:
        //Question australiaQuestion= new Question()
       
        
        if(buttonGroup1.getSelection()==null)
        {    
            CheckAnswerResult.setVisible(false);
            jLabelDiceResult.setText("Please make a selection");
        }
        else
        {
            AustraliaQuestionWindow.setVisible(false);
            
            
        
         if(QuestionText.getText().contains("Who was the first Australian Prime Minister?"))
        {
             if(!(jRadioButton2.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                    pointsDisplay.setText(" "+points);
            }

        }
        else if(QuestionText.getText().contains("Near which Victorian beach"))
        {
             if(!(jRadioButton3.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                    pointsDisplay.setText(" "+points);
            }
            

        }
         else if(QuestionText.getText().contains("Which Australian Prime Minister"))
        {
             if(!(jRadioButton4.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                    pointsDisplay.setText(" "+points);
            }
         
            

        }
         else if(QuestionText.getText().contains("Which was the last colony"))
        {
            if(!(jRadioButton3.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                    pointsDisplay.setText(" "+points);
            }

        }
         else if(QuestionText.getText().contains("Where did the Commonwealth"))
        {
             if(!(jRadioButton3.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                    pointsDisplay.setText(" "+points);
            }
            
            

        }
        //
        else if(QuestionText.getText().contains("In which year was the Blue Ensign"))
        {
             if(!(jRadioButton2.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                    pointsDisplay.setText(" "+points);
            }
            

        }
          buttonGroup1.clearSelection();
        
        }  
        
        
        
       // CheckAnswerResult.setVisible(true);
        //CheckAnswerResult.setText("Correct");
    }//GEN-LAST:event_submitButtonMouseClicked

    private void CheckAnswerResultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckAnswerResultMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CheckAnswerResultMouseEntered

    private void buttonAfricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAfricaMouseClicked
        // TODO add your handling code here:
        Africa a = new Africa();
        a.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonAfricaMouseClicked

    private void buttonNorthAmericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNorthAmericaMouseClicked
        // TODO add your handling code here:
        NorthAmerica n= new NorthAmerica();
        n.setVisible(true);
        this.setVisible(true);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonNorthAmericaMouseClicked

    private void buttonSouthAmericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSouthAmericaMouseClicked
        // TODO add your handling code here:
        SouthAmerica sa = new SouthAmerica();
        sa.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonSouthAmericaMouseClicked

    private void buttonSouthAmericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSouthAmericaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSouthAmericaActionPerformed

    private void buttonEuropeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEuropeMouseClicked
        // TODO add your handling code here:
        Europe e = new Europe();
        e.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonEuropeMouseClicked

    private void buttonAsiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAsiaMouseClicked
        // TODO add your handling code here:
        Asia a = new Asia();
        a.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonAsiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Australia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Australia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Australia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Australia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Australia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AustraliaQuestionWindow;
    private javax.swing.JLabel CheckAnswerResult;
    private javax.swing.JLabel DiceAustralia;
    private javax.swing.JLabel LabelPointsNeeded;
    private javax.swing.JLabel QuestionText;
    private javax.swing.JButton buttonAfrica;
    private javax.swing.JButton buttonAsia;
    private javax.swing.JButton buttonEurope;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonNorthAmerica;
    private javax.swing.JButton buttonSouthAmerica;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialogNewContinent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDiceResult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel pointsDisplay;
    private javax.swing.JLabel pointsLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
