/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Game;

import java.util.Random;

/**
 *
 * @author Lloyd
 */
public class Europe extends javax.swing.JFrame {

    /**
     * Creates new form Europe
     */
    
    
    EuropeQuestion eu= new EuropeQuestion();
    int points=0;
    
    public Europe() {
        initComponents();
        europeQuestionWindow.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialogNewContinent = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonNorthAmerica = new javax.swing.JButton();
        buttonSouthAmerica = new javax.swing.JButton();
        buttonAustralia = new javax.swing.JButton();
        buttonAfrica = new javax.swing.JButton();
        buttonAsia = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        DiceEurope = new javax.swing.JLabel();
        backButtonEurope = new javax.swing.JButton();
        europeQuestionWindow = new javax.swing.JPanel();
        submit = new javax.swing.JButton();
        jLabelDiceResult = new javax.swing.JLabel();
        questiontext = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        CheckAnswerResult = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pointsLabel = new javax.swing.JLabel();
        pointsDisplay = new javax.swing.JLabel();
        LabelPointsNeeded = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jDialogNewContinent.setMinimumSize(new java.awt.Dimension(550, 550));
        jDialogNewContinent.setPreferredSize(new java.awt.Dimension(550, 550));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("You are an expert on European history! Choose your next destination:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Congratulations!!");

        buttonNorthAmerica.setText("North America");
        buttonNorthAmerica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNorthAmericaMouseClicked(evt);
            }
        });

        buttonSouthAmerica.setText("South America");
        buttonSouthAmerica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSouthAmericaMouseClicked(evt);
            }
        });
        buttonSouthAmerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSouthAmericaActionPerformed(evt);
            }
        });

        buttonAustralia.setText("Australia");
        buttonAustralia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAustraliaMouseClicked(evt);
            }
        });
        buttonAustralia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAustraliaActionPerformed(evt);
            }
        });

        buttonAfrica.setText("Africa");
        buttonAfrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAfricaMouseClicked(evt);
            }
        });

        buttonAsia.setText("Asia");
        buttonAsia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAsiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialogNewContinentLayout = new javax.swing.GroupLayout(jDialogNewContinent.getContentPane());
        jDialogNewContinent.getContentPane().setLayout(jDialogNewContinentLayout);
        jDialogNewContinentLayout.setHorizontalGroup(
            jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                    .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                        .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel6))
                            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonSouthAmerica)
                                    .addComponent(buttonAustralia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonNorthAmerica, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAfrica, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAsia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogNewContinentLayout.setVerticalGroup(
            jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonNorthAmerica)
                .addGap(18, 18, 18)
                .addComponent(buttonSouthAmerica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAustralia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAsia)
                .addGap(18, 18, 18)
                .addComponent(buttonAfrica, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        DiceEurope.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/southamericabackground/dice-md.png"))); // NOI18N
        DiceEurope.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiceEuropeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DiceEuropeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DiceEuropeMouseEntered(evt);
            }
        });

        backButtonEurope.setBackground(new java.awt.Color(0, 153, 204));
        backButtonEurope.setForeground(new java.awt.Color(240, 240, 240));
        backButtonEurope.setText("Back");
        backButtonEurope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonEuropeActionPerformed(evt);
            }
        });

        submit.setText("submit");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });

        jLabelDiceResult.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout europeQuestionWindowLayout = new javax.swing.GroupLayout(europeQuestionWindow);
        europeQuestionWindow.setLayout(europeQuestionWindowLayout);
        europeQuestionWindowLayout.setHorizontalGroup(
            europeQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(europeQuestionWindowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(europeQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(europeQuestionWindowLayout.createSequentialGroup()
                .addGroup(europeQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(europeQuestionWindowLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelDiceResult, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(europeQuestionWindowLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit))
                    .addComponent(questiontext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        europeQuestionWindowLayout.setVerticalGroup(
            europeQuestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, europeQuestionWindowLayout.createSequentialGroup()
                .addComponent(jLabelDiceResult, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questiontext, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox4)
                .addGap(16, 16, 16)
                .addComponent(submit)
                .addContainerGap())
        );

        CheckAnswerResult.setFont(new java.awt.Font("Century", 1, 48)); // NOI18N
        CheckAnswerResult.setForeground(new java.awt.Color(0, 255, 0));
        CheckAnswerResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckAnswerResultMouseEntered(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 255));
        jLabel5.setText("Click on the dice to roll it");

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome to Europe!");

        pointsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        pointsLabel.setForeground(new java.awt.Color(255, 255, 255));
        pointsLabel.setText("Points:");

        pointsDisplay.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        pointsDisplay.setForeground(new java.awt.Color(255, 255, 255));
        pointsDisplay.setText("0");

        LabelPointsNeeded.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelPointsNeeded.setForeground(new java.awt.Color(255, 255, 255));
        LabelPointsNeeded.setText("Beat this level by earning 40,000 points!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pointsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pointsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(backButtonEurope))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(DiceEurope))))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckAnswerResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(europeQuestionWindow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(LabelPointsNeeded)))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelPointsNeeded)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pointsLabel)
                    .addComponent(pointsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(58, 58, 58)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CheckAnswerResult, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(europeQuestionWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DiceEurope)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButtonEurope)
                        .addGap(40, 40, 40))))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/neweurope.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DiceEuropeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceEuropeMouseClicked
 Random roll= new Random();
        int result= 1+ roll.nextInt(6);//int between 1-6 inclusive
        europeQuestionWindow.setVisible(true);
        questiontext.setText(eu.showQuestion());
        
        if(questiontext.getText().contains("The government that replaced Napoleon"))
        {
             jCheckBox1.setText("Constitutional Monarchy");
             jCheckBox2.setText("Obamacare");
             jCheckBox3.setText("Democracy");
             jCheckBox4.setText("Batman");
        }
        else if(questiontext.getText().contains("The Peace of Westphalia"))
        {
             jCheckBox1.setText("absolutely nothing");
             jCheckBox2.setText("marked the end of the Twenty Years War");
             jCheckBox3.setText("marked the end of the Thirty Years War");
             jCheckBox4.setText("switched to Geico");
        }
        else if(questiontext.getText().contains("The defeat of the Spanish Armada"))
        {
             jCheckBox1.setText("good stuff");
             jCheckBox2.setText("Encourage Catholicism in Europe");
             jCheckBox3.setText("bad stuff");
             jCheckBox4.setText("questionable stuff");
        }
        else if(questiontext.getText().contains("The greatest flaw"))
        {
             jCheckBox1.setText("no indigenous inhabitants there to kill");
             jCheckBox2.setText("he underestimated the circumfrence of the earth");
             jCheckBox3.setText("no boat insurance");
             jCheckBox4.setText("bad weather");
        }
        else if(questiontext.getText().contains("The Edict of Nantes"))
        {
             jCheckBox1.setText("recognizing the importance of the military in state affairs");
             jCheckBox2.setText("limiting the power of the king in religious matters");
             jCheckBox3.setText("religious tolerance for the Huguenots");
             jCheckBox4.setText("establishing control of the Estates General over the king");
        }
        else if(questiontext.getText().contains("Among the food plants"))
        {
             jCheckBox1.setText("the potato");
             jCheckBox2.setText("KFC");
             jCheckBox3.setText("Spinach");
             jCheckBox4.setText("Cabbage");
        }
         //answers paired with questions
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        if(result==1)
        {
            jLabelDiceResult.setText("You rolled a 1!");
            //a
        }
        if(result==2)
        {
            jLabelDiceResult.setText("You rolled a 2!");
            
        }
        if(result==3)
        {
            jLabelDiceResult.setText("You rolled a 3!");
            
        }
        if(result==4)
        {
            jLabelDiceResult.setText("You rolled a 4!");
            
        }
        if(result==5)
        {
            jLabelDiceResult.setText("You rolled a 5!");
            
        }
        if(result==6)
        {
            jLabelDiceResult.setText("You rolled a 6!");
        }
        //invoke a JDialog with the question.
        //have jdialog close on submit
        //rinse and repeat for other continents
        //find a way to move a panel by (int)result
                             
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_DiceEuropeMouseClicked

    private void DiceEuropeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceEuropeMouseEntered
        // TODO add your handling code here:
        DiceEurope.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
         if(points>=40000)
        {
        //dialog box for moving to another continent
            jDialogNewContinent.setVisible(true);
            
        }
    }//GEN-LAST:event_DiceEuropeMouseEntered

    private void DiceEuropeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceEuropeMouseExited
            // TODO add your handling code here:
        DiceEurope.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_DiceEuropeMouseExited

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        europeQuestionWindow.setVisible(false);
        
        
        CheckAnswerResult.setVisible(false);

        if(questiontext.getText().contains("The government that replaced Napoleon"))
        {

            //jradiobutton2
            if(!(jCheckBox1.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*10;
                pointsDisplay.setText(" "+points);
            }
        }
        else if(questiontext.getText().contains("The Peace of Westphalia"))
        {

            //jradiobutton2
            if(!(jCheckBox3.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*10;
                 pointsDisplay.setText(" "+points);
                
            }
        }
        
        //"The defeat of the Spanish Armada"
        else if(questiontext.getText().contains("The defeat of the Spanish Armada"))
        {

            //jradiobutton2
            if(!(jCheckBox2.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*10;
                pointsDisplay.setText(" "+points);
            }
        }
        else if(questiontext.getText().contains("The greatest flaw"))
        {

            //jradiobutton2
            if(!(jCheckBox2.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*10;
                pointsDisplay.setText(" "+points);
            }
        } 
        
        else if(questiontext.getText().contains("Edict of Nantes"))
        {

            //jradiobutton2
            if(!(jCheckBox3.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*10;
                pointsDisplay.setText(" "+points);
            }
        }
         else if(questiontext.getText().contains("Among the food plants"))
        {

            //jradiobutton2
            if(!(jCheckBox2.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*10;
                pointsDisplay.setText(" "+points);
            }
        }
        
        
    }//GEN-LAST:event_submitMouseClicked

    private void CheckAnswerResultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckAnswerResultMouseEntered
        // TODO add your handling code here:
        CheckAnswerResult.setText(null);
    }//GEN-LAST:event_CheckAnswerResultMouseEntered

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void backButtonEuropeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonEuropeActionPerformed
        ContinentSelection cs = new ContinentSelection();
        cs.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonEuropeActionPerformed

    private void buttonNorthAmericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNorthAmericaMouseClicked
        // TODO add your handling code here:
        NorthAmerica n= new NorthAmerica();
        n.setVisible(true);
        this.setVisible(true);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonNorthAmericaMouseClicked

    private void buttonSouthAmericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSouthAmericaMouseClicked
        // TODO add your handling code here:
        SouthAmerica sa = new SouthAmerica();
        sa.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonSouthAmericaMouseClicked

    private void buttonSouthAmericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSouthAmericaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSouthAmericaActionPerformed

    private void buttonAustraliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAustraliaMouseClicked
        // TODO add your handling code here:
        Australia au = new Australia();
        au.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonAustraliaMouseClicked

    private void buttonAustraliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAustraliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAustraliaActionPerformed

    private void buttonAfricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAfricaMouseClicked
        // TODO add your handling code here:
        Africa a = new Africa();
        a.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonAfricaMouseClicked

    private void buttonAsiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAsiaMouseClicked
        // TODO add your handling code here:
        Asia a = new Asia();
        a.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonAsiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Europe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Europe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Europe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Europe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Europe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CheckAnswerResult;
    private javax.swing.JLabel DiceEurope;
    private javax.swing.JLabel LabelPointsNeeded;
    private javax.swing.JButton backButtonEurope;
    private javax.swing.JButton buttonAfrica;
    private javax.swing.JButton buttonAsia;
    private javax.swing.JButton buttonAustralia;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonNorthAmerica;
    private javax.swing.JButton buttonSouthAmerica;
    private javax.swing.JPanel europeQuestionWindow;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JDialog jDialogNewContinent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDiceResult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pointsDisplay;
    private javax.swing.JLabel pointsLabel;
    private javax.swing.JLabel questiontext;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
