/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Game;

import java.util.Random;

/**
 *
 * @author Lloyd
 */
public class NorthAmerica extends javax.swing.JFrame {

    /**
     * Creates new form NorthAmerica
     */
    NorthAmericaQuestion na= new NorthAmericaQuestion();
    int points=0;
    
    public NorthAmerica() {
        initComponents();
        NAquestionWindow.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDialogNewContinent = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonSouthAmerica = new javax.swing.JButton();
        buttonAustralia = new javax.swing.JButton();
        buttonAfrica = new javax.swing.JButton();
        buttonEurope = new javax.swing.JButton();
        buttonAsia = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        DiceNorthAmerica = new javax.swing.JLabel();
        northAmericaBack = new javax.swing.JButton();
        NAquestionWindow = new javax.swing.JPanel();
        questiontext = new javax.swing.JLabel();
        jLabelDiceResult = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        answerBox = new javax.swing.JTextField();
        CheckAnswerResult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pointsLabel = new javax.swing.JLabel();
        pointsDisplay = new javax.swing.JLabel();
        northamericabackground = new javax.swing.JLabel();

        jDialogNewContinent.setMinimumSize(new java.awt.Dimension(550, 550));
        jDialogNewContinent.setPreferredSize(new java.awt.Dimension(550, 550));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Congratulations!!");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("You are an expert on North American history! Choose your next destination:");

        buttonSouthAmerica.setText("South America");
        buttonSouthAmerica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSouthAmericaMouseClicked(evt);
            }
        });
        buttonSouthAmerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSouthAmericaActionPerformed(evt);
            }
        });

        buttonAustralia.setText("Australia");
        buttonAustralia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAustraliaMouseClicked(evt);
            }
        });
        buttonAustralia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAustraliaActionPerformed(evt);
            }
        });

        buttonAfrica.setText("Africa");
        buttonAfrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAfricaMouseClicked(evt);
            }
        });

        buttonEurope.setText("Europe");
        buttonEurope.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEuropeMouseClicked(evt);
            }
        });

        buttonAsia.setText("Asia");
        buttonAsia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAsiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialogNewContinentLayout = new javax.swing.GroupLayout(jDialogNewContinent.getContentPane());
        jDialogNewContinent.getContentPane().setLayout(jDialogNewContinentLayout);
        jDialogNewContinentLayout.setHorizontalGroup(
            jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
                    .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonAfrica, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSouthAmerica)
                            .addComponent(buttonAustralia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonEurope, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAsia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogNewContinentLayout.setVerticalGroup(
            jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(buttonSouthAmerica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAfrica, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAustralia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonEurope, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAsia)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 581));
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setOpaque(false);

        DiceNorthAmerica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/southamericabackground/dice-md.png"))); // NOI18N
        DiceNorthAmerica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DiceNorthAmericaMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiceNorthAmericaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DiceNorthAmericaMouseEntered(evt);
            }
        });

        northAmericaBack.setBackground(new java.awt.Color(0, 153, 204));
        northAmericaBack.setForeground(new java.awt.Color(255, 255, 255));
        northAmericaBack.setText("Back");
        northAmericaBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                northAmericaBackActionPerformed(evt);
            }
        });

        questiontext.setAutoscrolls(true);

        jLabelDiceResult.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelDiceResult.setToolTipText("");

        submit.setText("submit");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NAquestionWindowLayout = new javax.swing.GroupLayout(NAquestionWindow);
        NAquestionWindow.setLayout(NAquestionWindowLayout);
        NAquestionWindowLayout.setHorizontalGroup(
            NAquestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NAquestionWindowLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NAquestionWindowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NAquestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NAquestionWindowLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(questiontext, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NAquestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NAquestionWindowLayout.createSequentialGroup()
                            .addComponent(answerBox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NAquestionWindowLayout.createSequentialGroup()
                            .addComponent(jLabelDiceResult, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        NAquestionWindowLayout.setVerticalGroup(
            NAquestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NAquestionWindowLayout.createSequentialGroup()
                .addComponent(jLabelDiceResult, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questiontext, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(answerBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(19, 19, 19))
        );

        CheckAnswerResult.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        CheckAnswerResult.setForeground(new java.awt.Color(0, 153, 0));
        CheckAnswerResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckAnswerResultMouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Welcome to North America!");

        pointsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        pointsLabel.setForeground(new java.awt.Color(255, 255, 255));
        pointsLabel.setText("Points:");

        pointsDisplay.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        pointsDisplay.setForeground(new java.awt.Color(255, 255, 255));
        pointsDisplay.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(northAmericaBack)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DiceNorthAmerica)
                        .addGap(5, 5, 5)))
                .addComponent(NAquestionWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckAnswerResult, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pointsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pointsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckAnswerResult, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pointsLabel)
                            .addComponent(pointsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NAquestionWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(DiceNorthAmerica)
                        .addGap(116, 116, 116)
                        .addComponent(northAmericaBack)
                        .addGap(66, 66, 66))))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel2, gridBagConstraints);

        northamericabackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/NorthAmericaBackground/newnorthamerica.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(northamericabackground, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DiceNorthAmericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceNorthAmericaMouseClicked
        // TODO add your handling code here:
       
        Random roll= new Random();
        int result= 1+ roll.nextInt(6);//int between 1-6 inclusive
        NAquestionWindow.setVisible(true);
        
        
            
        
       
        
        //jLabelDiceResult.setText(String.valueOf(piece.getLocation()));
        questiontext.setText(na.showQuestion());
        
        if(result==1)
        {
            jLabelDiceResult.setText("You rolled a 1!");
            //questiontext.setText(na.showQuestion());
            
           
        }
        if(result==2)
        {
            jLabelDiceResult.setText("You rolled a 2!");
            
           
        }
        if(result==3)
        {
            jLabelDiceResult.setText("You rolled a 3!");
            
        }
        if(result==4)
        {
            jLabelDiceResult.setText("You rolled a 4!");
            
        }
        if(result==5)
        {
            jLabelDiceResult.setText("You rolled a 5!");
            
        }
        if(result==6)
        {
            jLabelDiceResult.setText("You rolled a 6!");
            
        }
        
        
        //invoke a JDialog with the question.
        //have jdialog close on submit
        //rinse and repeat for other continents
        //find a way to move a panel by (int)result
 
          
        
    }//GEN-LAST:event_DiceNorthAmericaMouseClicked

    private void DiceNorthAmericaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceNorthAmericaMouseEntered
        // TODO add your handling code here:
        DiceNorthAmerica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        if(points>=40000)
        {
        //dialog box for moving to another continent
            jDialogNewContinent.setVisible(true);
            
        }
    }//GEN-LAST:event_DiceNorthAmericaMouseEntered

    private void DiceNorthAmericaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceNorthAmericaMouseExited
        // TODO add your handling code here:
        DiceNorthAmerica.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_DiceNorthAmericaMouseExited

    private void northAmericaBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_northAmericaBackActionPerformed
        // TODO add your handling code here:
        ContinentSelection cs = new ContinentSelection();
        cs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_northAmericaBackActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        //THE CODE BELOW CHECKS ANSWERS
        //
    
    if(!(answerBox.getText().isEmpty()))//if it's not empty, check to see what's in there
    {       
        if(questiontext.getText().contains("Who was"))//now we know its about the presidents
        {
     
            
            //the right answer is
            if(answerBox.getText().equalsIgnoreCase("George Washington"))
            {
                    CheckAnswerResult.setText("CORRECT!!");
                    answerBox.setText(null);
                    points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                    //NAquestionWindow.setVisible(false);
                    pointsDisplay.setText(""+points);
       
            
            }
            else
            {
                    CheckAnswerResult.setText("WRONG!");
                    answerBox.setText(null);
                   // NAquestionWindow.setVisible(false);
            }
        
        
        }
         if(questiontext.getText().contains("What year"))//now we know its about the presidents
        {
            
            //the right answer is
            if(answerBox.getText().equals("1959"))
            {
                    CheckAnswerResult.setText("CORRECT!!");
                    answerBox.setText(null);
                   points+= (int)(jLabelDiceResult.getText().charAt(13))*100;//casting to make the dice number an integer
                    //NAquestionWindow.setVisible(false);
                  // char testing=jLabelDiceResult.getText().charAt(13);//make sure it's getting the right value
                   pointsDisplay.setText(" "+points);
            }
            else
            {
                    CheckAnswerResult.setText("WRONG!");
                    answerBox.setText(null);
                    //NAquestionWindow.setVisible(false);
            }
        
        
        }
        if(questiontext.getText().contains("War of 1812"))//
        {
            
            //the right answer is
            if(answerBox.getText().equalsIgnoreCase("Treaty of Ghent"))
            {
                    CheckAnswerResult.setText("CORRECT!!");
                    answerBox.setText(null);
                    points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                   
                    pointsDisplay.setText(" "+points);
            
            }
            else
            {
                    CheckAnswerResult.setText("WRONG!");
                    answerBox.setText(null);
                    //NAquestionWindow.setVisible(false);
            }
            
        
        }
         if(questiontext.getText().contains("What happened"))//now we know its about the presidents
        {
            
            //the right answer is
            if(answerBox.getText().equalsIgnoreCase("Battle of Fort Sumter"))
            {
                    CheckAnswerResult.setText("CORRECT!!");
                    answerBox.setText(null);
                    points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                    pointsDisplay.setText(" "+points);
                   // NAquestionWindow.setVisible(false);
            
            }
            else
            {
                    CheckAnswerResult.setText("WRONG!");
                    answerBox.setText(null);
                    //NAquestionWindow.setVisible(false);
            }
        
         }
              NAquestionWindow.setVisible(false);       
        }

    else
    {
        jLabelDiceResult.setText("Enter an answer please");
    
    }
        
     
         
     
        
        
        //answerBox.setText(null);
        //DISTRIBUTE CODE BELOW TO ALL CONTINENT CLASSES
       
       // TODO add your handling code here:
    }//GEN-LAST:event_submitMouseClicked

    private void CheckAnswerResultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckAnswerResultMouseEntered
        // TODO add your handling code here:
        CheckAnswerResult.setText(null);
    }//GEN-LAST:event_CheckAnswerResultMouseEntered

    private void buttonAustraliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAustraliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAustraliaActionPerformed

    private void buttonSouthAmericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSouthAmericaMouseClicked
        // TODO add your handling code here:
         SouthAmerica sa = new SouthAmerica();
         sa.setVisible(true);
         this.setVisible(false);
         jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonSouthAmericaMouseClicked

    private void buttonAfricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAfricaMouseClicked
        // TODO add your handling code here:
        Africa a = new Africa();
         a.setVisible(true);
         this.setVisible(false);
         jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonAfricaMouseClicked

    private void buttonAustraliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAustraliaMouseClicked
        // TODO add your handling code here:
        Australia au = new Australia();
         au.setVisible(true);
         this.setVisible(false);
         jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonAustraliaMouseClicked

    private void buttonEuropeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEuropeMouseClicked
        // TODO add your handling code here:
        Europe e = new Europe();
        e.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonEuropeMouseClicked

    private void buttonAsiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAsiaMouseClicked
        // TODO add your handling code here:
        Asia a = new Asia();
         a.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonAsiaMouseClicked

    private void buttonSouthAmericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSouthAmericaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSouthAmericaActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NorthAmerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NorthAmerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NorthAmerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NorthAmerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NorthAmerica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CheckAnswerResult;
    private javax.swing.JLabel DiceNorthAmerica;
    private javax.swing.JPanel NAquestionWindow;
    private javax.swing.JTextField answerBox;
    private javax.swing.JButton buttonAfrica;
    private javax.swing.JButton buttonAsia;
    private javax.swing.JButton buttonAustralia;
    private javax.swing.JButton buttonEurope;
    private javax.swing.JButton buttonSouthAmerica;
    private javax.swing.JDialog jDialogNewContinent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDiceResult;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton northAmericaBack;
    private javax.swing.JLabel northamericabackground;
    private javax.swing.JLabel pointsDisplay;
    private javax.swing.JLabel pointsLabel;
    private javax.swing.JLabel questiontext;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
