/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package Game;
import java.util.Random;
/**
 *
 * @author Lloyd
 */
public class SouthAmerica extends javax.swing.JFrame{
    

           
    /**
     * Creates new form SouthAmerica
     */
    SouthAmericaQuestion sa = new SouthAmericaQuestion();//instantiating question model for south america
    int points=0;
    public SouthAmerica() {
        initComponents();
        SAquestionWindow.setVisible(false);//set true on dice event.
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialogNewContinent = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonNorthAmerica = new javax.swing.JButton();
        buttonAsia = new javax.swing.JButton();
        buttonEurope = new javax.swing.JButton();
        buttonAfrica = new javax.swing.JButton();
        buttonAustralia = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DiceSouthAmerica = new javax.swing.JLabel();
        backSouthAmerica = new javax.swing.JButton();
        SAquestionWindow = new javax.swing.JPanel();
        submit = new javax.swing.JButton();
        questiontext = new javax.swing.JLabel();
        jLabelDiceResult = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        CheckAnswerResult = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pointsLabel = new javax.swing.JLabel();
        pointsDisplay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SouthAmericaBackground = new javax.swing.JLabel();

        jDialogNewContinent.setMinimumSize(new java.awt.Dimension(550, 550));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Congratulations!!");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("You are an expert on South American history! Choose your next destination:");

        buttonNorthAmerica.setText("North America");
        buttonNorthAmerica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNorthAmericaMouseClicked(evt);
            }
        });

        buttonAsia.setText("Asia");
        buttonAsia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAsiaMouseClicked(evt);
            }
        });

        buttonEurope.setText("Europe");
        buttonEurope.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEuropeMouseClicked(evt);
            }
        });

        buttonAfrica.setText("Africa");
        buttonAfrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAfricaMouseClicked(evt);
            }
        });

        buttonAustralia.setText("Australia");
        buttonAustralia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAustraliaMouseClicked(evt);
            }
        });
        buttonAustralia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAustraliaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogNewContinentLayout = new javax.swing.GroupLayout(jDialogNewContinent.getContentPane());
        jDialogNewContinent.getContentPane().setLayout(jDialogNewContinentLayout);
        jDialogNewContinentLayout.setHorizontalGroup(
            jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                        .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel6))
                            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonEurope, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonNorthAmerica, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAfrica, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAsia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAustralia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogNewContinentLayout.setVerticalGroup(
            jDialogNewContinentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewContinentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonNorthAmerica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAustralia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAsia)
                .addGap(18, 18, 18)
                .addComponent(buttonEurope, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAfrica, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Welcome to South America!");

        DiceSouthAmerica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/southamericabackground/dice-md.png"))); // NOI18N
        DiceSouthAmerica.setText("Click Dice ");
        DiceSouthAmerica.setMaximumSize(new java.awt.Dimension(200, 200));
        DiceSouthAmerica.setMinimumSize(new java.awt.Dimension(200, 200));
        DiceSouthAmerica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiceSouthAmericaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DiceSouthAmericaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DiceSouthAmericaMouseEntered(evt);
            }
        });

        backSouthAmerica.setBackground(new java.awt.Color(0, 153, 204));
        backSouthAmerica.setForeground(new java.awt.Color(255, 255, 255));
        backSouthAmerica.setText("Back");
        backSouthAmerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSouthAmericaActionPerformed(evt);
            }
        });

        submit.setText("Submit");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });

        jLabelDiceResult.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        buttonGroup1.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);

        buttonGroup1.add(jRadioButton3);

        buttonGroup1.add(jRadioButton4);

        javax.swing.GroupLayout SAquestionWindowLayout = new javax.swing.GroupLayout(SAquestionWindow);
        SAquestionWindow.setLayout(SAquestionWindowLayout);
        SAquestionWindowLayout.setHorizontalGroup(
            SAquestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SAquestionWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SAquestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SAquestionWindowLayout.createSequentialGroup()
                        .addGroup(SAquestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(questiontext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(SAquestionWindowLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(submit)))
                        .addGap(18, 18, 18))
                    .addGroup(SAquestionWindowLayout.createSequentialGroup()
                        .addComponent(jLabelDiceResult, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(42, Short.MAX_VALUE))))
            .addGroup(SAquestionWindowLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(SAquestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SAquestionWindowLayout.setVerticalGroup(
            SAquestionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SAquestionWindowLayout.createSequentialGroup()
                .addComponent(jLabelDiceResult, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questiontext, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(submit)
                .addContainerGap())
        );

        CheckAnswerResult.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        CheckAnswerResult.setForeground(new java.awt.Color(0, 255, 0));
        CheckAnswerResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckAnswerResultMouseEntered(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Click on the dice to roll it");

        pointsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        pointsLabel.setForeground(new java.awt.Color(255, 255, 255));
        pointsLabel.setText("Points:");

        pointsDisplay.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        pointsDisplay.setForeground(new java.awt.Color(255, 255, 255));
        pointsDisplay.setText("0");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Beat this level by earning 40,000 points!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(DiceSouthAmerica, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(112, 112, 112)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(backSouthAmerica))))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckAnswerResult, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(SAquestionWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 102, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(pointsLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pointsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(103, 103, 103)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pointsLabel)
                    .addComponent(pointsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(CheckAnswerResult, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DiceSouthAmerica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(backSouthAmerica))
                            .addComponent(SAquestionWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        SouthAmericaBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/southamericabackground/newsouthamerica.jpg"))); // NOI18N
        SouthAmericaBackground.setPreferredSize(new java.awt.Dimension(800, 551));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(SouthAmericaBackground, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckAnswerResultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckAnswerResultMouseEntered
        // TODO add your handling code here:
        CheckAnswerResult.setText(null);
    }//GEN-LAST:event_CheckAnswerResultMouseEntered

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        
  if(buttonGroup1.getSelection()==null)
    {    
      CheckAnswerResult.setVisible(false);
      jLabelDiceResult.setText("Please make a selection");
    }
  else
    {
            SAquestionWindow.setVisible(false);
            

        
        if(questiontext.getText().contains("What year did the Portuguese invade Brazil?"))
        {

            //jradiobutton2
            if(!(jRadioButton2.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                    pointsDisplay.setText(" "+points);

            }
        }
        else if(questiontext.getText().contains("What are people"))
        {
            if(!(jRadioButton3.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                    pointsDisplay.setText(" "+points);
            }
        }
        else if(questiontext.getText().contains("Who captured "))
        {

            if(!(jRadioButton2.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                    pointsDisplay.setText(" "+points);
            }
        }
        else if(questiontext.getText().contains("Who overthrew "))
        {
            if(!(jRadioButton4.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                    pointsDisplay.setText(" "+points);
            }
        }
        else if(questiontext.getText().contains("He named the Pacific Ocean."))
        {
            if(!(jRadioButton2.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                    pointsDisplay.setText(" "+points);
            }
        }

        else if(questiontext.getText().contains("Which of these is a major river in South America?"))
        {
            if(!(jRadioButton2.isSelected()))
            {
                CheckAnswerResult.setVisible(true);
                CheckAnswerResult.setText("WRONG");
            }
            else
            {
                CheckAnswerResult.setVisible(true);

                CheckAnswerResult.setText("Correct!!");
                points+= (int)jLabelDiceResult.getText().charAt(13)*100;
                    pointsDisplay.setText(" "+points);
            }
        }
        SAquestionWindow.setVisible(false);
        buttonGroup1.clearSelection();//so that nothing is selected when the box pops up again
    }
        
        

    }//GEN-LAST:event_submitMouseClicked

    private void backSouthAmericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSouthAmericaActionPerformed
        // TODO add your handling code here:
        ContinentSelection cs = new ContinentSelection();
        cs.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_backSouthAmericaActionPerformed

    private void DiceSouthAmericaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceSouthAmericaMouseEntered
        // TODO add your handling code here:
        DiceSouthAmerica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
         if(points>=40000)
        {
        //dialog box for moving to another continent
            jDialogNewContinent.setVisible(true);
            
        }
    }//GEN-LAST:event_DiceSouthAmericaMouseEntered

    private void DiceSouthAmericaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceSouthAmericaMouseExited
        // TODO add your handling code here:
        DiceSouthAmerica.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_DiceSouthAmericaMouseExited

    private void DiceSouthAmericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiceSouthAmericaMouseClicked
        // TODO add your handling code here:
        Random roll= new Random();
        int result= 1+ roll.nextInt(6);//int between 1-6 inclusive
        SAquestionWindow.setVisible(true);

        questiontext.setText(sa.showQuestion());//sets returned string as question

        if(questiontext.getText().contains("What year did the Portuguese invade Brazil?"))
        {

            jRadioButton1.setText("1501");
            jRadioButton2.setText("1500");//correct
            jRadioButton3.setText("1499");
            jRadioButton4.setText("1498");

        }
        else if(questiontext.getText().contains("What are people"))
        {
            jRadioButton1.setText("Mulattos");
            jRadioButton2.setText("Ameripeans");
            jRadioButton3.setText("Mestizos");//correct
            jRadioButton4.setText("Aztecas");

        }
        else if(questiontext.getText().contains("Who captured "))
        {
            jRadioButton1.setText("George Washington");
            jRadioButton2.setText("Jason Fromal");
            jRadioButton3.setText("Francisco Pizarro");//correct
            jRadioButton4.setText("Bill Burr");
        }
        else if(questiontext.getText().contains("Who overthrew "))
        {
            jRadioButton1.setText("Vasco da Gama");
            jRadioButton2.setText("Ferdinand Magellan");
            jRadioButton3.setText("Lloyd T. Slade");
            jRadioButton4.setText("Augusto Pinochet");//correct
        }
        //He named the Pacific Ocean.
        else if(questiontext.getText().contains("He named the Pacific Ocean."))
        {
            jRadioButton1.setText("Christopher Columbus");
            jRadioButton2.setText("Ferdinand Magellan");//correct
            jRadioButton3.setText("Francisco Pizarro");
            jRadioButton4.setText("Augusto Pinochet");
        }
        else if(questiontext.getText().contains("Which of these is a major river in South America?"))
        {
            jRadioButton1.setText("Rio de Plata");
            jRadioButton2.setText("Orinoco");
            jRadioButton3.setText("Amazon");
            jRadioButton4.setText("All of these");//correct
        }

        if(result==1)
        {
            jLabelDiceResult.setText("You rolled a 1!");
            //a

        }
        if(result==2)
        {
            jLabelDiceResult.setText("You rolled a 2!");

        }
        if(result==3)
        {
            jLabelDiceResult.setText("You rolled a 3!");

        }
        if(result==4)
        {
            jLabelDiceResult.setText("You rolled a 4!");

        }
        if(result==5)
        {
            jLabelDiceResult.setText("You rolled a 5!");

        }
        if(result==6)
        {
            jLabelDiceResult.setText("You rolled a 6!");
        }
        //invoke a JDialog with the question.
        //have jdialog close on submit
        //rinse and repeat for other continents
        //find a way to move a panel by (int)result

    }//GEN-LAST:event_DiceSouthAmericaMouseClicked

    private void buttonNorthAmericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNorthAmericaMouseClicked
        // TODO add your handling code here:
        NorthAmerica n= new NorthAmerica();
        n.setVisible(true);
        this.setVisible(true);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonNorthAmericaMouseClicked

    private void buttonAsiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAsiaMouseClicked
        // TODO add your handling code here:
        Asia a = new Asia();
        a.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonAsiaMouseClicked

    private void buttonEuropeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEuropeMouseClicked
        // TODO add your handling code here:
        Europe e = new Europe();
        e.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonEuropeMouseClicked

    private void buttonAfricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAfricaMouseClicked
        // TODO add your handling code here:
        Africa a = new Africa();
        a.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonAfricaMouseClicked

    private void buttonAustraliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAustraliaMouseClicked
        // TODO add your handling code here:
        Australia au = new Australia();
        au.setVisible(true);
        this.setVisible(false);
        jDialogNewContinent.dispose();
    }//GEN-LAST:event_buttonAustraliaMouseClicked

    private void buttonAustraliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAustraliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAustraliaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SouthAmerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SouthAmerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SouthAmerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SouthAmerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SouthAmerica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CheckAnswerResult;
    private javax.swing.JLabel DiceSouthAmerica;
    private javax.swing.JPanel SAquestionWindow;
    private javax.swing.JLabel SouthAmericaBackground;
    private javax.swing.JButton backSouthAmerica;
    private javax.swing.JButton buttonAfrica;
    private javax.swing.JButton buttonAsia;
    private javax.swing.JButton buttonAustralia;
    private javax.swing.JButton buttonEurope;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonNorthAmerica;
    private javax.swing.JDialog jDialogNewContinent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDiceResult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel pointsDisplay;
    private javax.swing.JLabel pointsLabel;
    private javax.swing.JLabel questiontext;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
